### ISSUE TITLE
Open in folder + help menu feature request

### ISSUE THREAD

**Issue by lispstudent** [fourier/mediaimport#15]
Thank you for mediaimport, I discovered it while searching for CAPI related code. Later I started using it to import files from cameras and phones. I do not know of any tools that fulfil this tasks so easily and perfectly, at least on Windows.

As I use it now almost daily, I wonder if would you consider adding the option "Open in folder", both as right click menu, and possibly as radio check-box (something like "When done: Open in folder")?

Also, would you consider adding a Help menu (next to "Media Import") with a few key information like,
- allowed output patterns,
- meaning of Use EXIF for JPG
- Examples of custom commands

Thank you again for mediaimport, it is a joyful tool.

**Comment by fourier** [comment]
Hi,
Not sure if I can create more advanced documentation, but I'll try. So far it is tooltips on windows.
But I can try to add "Open in folder" feature.

**Comment by lispstudent** [comment]
Thank you, I'll gladly test if needed at all.

I personally could do without such documentation, but I would like some not-so-skilled friends to use it too, and some "offline" help docs would help.

I tried hovering on top of checkboxes and other fields, but in my case I could not see tooltips.

**Comment by lispstudent** [comment]
PS: Would it be all right for me to request mediaimport to be added to [scoop](https://github.com/lukesampson/scoop)?

**Comment by fourier** [comment]
> PS: Would it be all right for me to request mediaimport to be added to [scoop](https://github.com/lukesampson/scoop)?

Sorry for late reply, maybe, I don't know what scoop is and how useful to have mediaimport there :)

**Comment by lispstudent** [comment]
It is just one of a few simple ways to deal with installs on Windows machines, another one being [choco](https://chocolatey.org/).

Not important for simple installs, but can be useful when one needs to deal with several dozen installs on several pcs, perhaps in a repeatable manner.

**Comment by fourier** [comment]
Finally had time to work a bit on this feature. Will do the new release soon.

**Comment by lispstudent** [comment]
Marvellous, thank you. Much to learn from the code, too.

**Comment by fourier** [comment]
A new release has been issued, https://github.com/fourier/mediaimport/releases
Please verify the option you have requested.

**Comment by lispstudent** [comment]
I tested on Windows 10 LTSC  using a complex folder+subfolders structure of photos taken on mixed dates, and all seem to work.

Unlike other tools, carrying a bit of "frazzle" with them, this app gives a feeling of serene trust. As said earlier, a joy to use.

I would have a few small other feature requests, but I wouldn't wish to burden its development. Would it be all right to open one or two more requests for your consideration?

**Comment by fourier** [comment]
Yes. Please sumbit them as separate issues for traceability.
